### ISSUE TITLE
action not working with chatroom

### ISSUE THREAD

**Issue by sachinbanugariya** [scalableminds/chatroom#100]
we are  using rasa chatbot with chatroom,

chatbot is working very well if we just run with backend.

but if we use and integrate chatbot with chatroom for frontend and when we try to run from browser then action response is not working.

logs_of_bot_run:
2019-05-13 14:11:59 DEBUG    rasa_core.tracker_store  - Recreating tracker for id 'e2af79b0-bbbe-42f1-be75-af1fc2db2808'
2019-05-13 14:11:59 WARNING  py.warnings  - /usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

2019-05-13 14:11:59 DEBUG    rasa_core.processor  - Received user message 'london' with intent '{'name': 'inform', 'confidence': 0.5954149948680351}' and entities '[{'start': 0, 'end': 6, 'value': 'london', 'entity': 'location', 'confidence': 0.45510354427538885, 'extractor': 'ner_crf'}]'
2019-05-13 14:11:59 DEBUG    rasa_core.processor  - Logged UserUtterance - tracker now has 11 events
2019-05-13 14:11:59 DEBUG    rasa_core.processor  - Current slot values:
        course: None
        location: london
        university: None
2019-05-13 14:11:59 DEBUG    rasa_core.policies.memoization  - Current tracker state [{'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'prev_utter_greet': 1.0, 'intent_greet': 1.0}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'prev_utter_ask_location': 1.0, 'intent_greet': 1.0}, {'prev_action_listen': 1.0, 'entity_location': 1.0, 'slot_location_0': 1.0, 'intent_inform': 1.0}]
2019-05-13 14:11:59 DEBUG    rasa_core.policies.memoization  - There is a memorised next action '5'
2019-05-13 14:11:59 DEBUG    rasa_core.policies.ensemble  - Predicted next action using policy_0_MemoizationPolicy
2019-05-13 14:11:59 DEBUG    rasa_core.processor  - Predicted next action 'action_uni' with prob 1.00.
2019-05-13 14:11:59 DEBUG    rasa_core.actions.action  - Calling action endpoint to run action 'action_uni'.
2019-05-13 14:11:59 ERROR    rasa_core.processor  - Encountered an exception while running action 'action_uni'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
2019-05-13 14:11:59 DEBUG    rasa_core.processor  - 404 Client Error: NOT FOUND for url: http://localhost:5055/webhook/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/rasa_core/processor.py", line 351, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/usr/local/lib/python3.6/dist-packages/rasa_core/actions/action.py", line 338, in run
    response.raise_for_status()
  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: NOT FOUND for url: http://localhost:5055/webhook/
2019-05-13 14:11:59 DEBUG    rasa_core.processor  - Action 'action_uni' ended with events '[]'
2019-05-13 14:11:59 DEBUG    rasa_core.policies.memoization  - Current tracker state [{'prev_utter_greet': 1.0, 'intent_greet': 1.0}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'prev_utter_ask_location': 1.0, 'intent_greet': 1.0}, {'prev_action_listen': 1.0, 'entity_location': 1.0, 'slot_location_0': 1.0, 'intent_inform': 1.0}, {'prev_action_uni': 1.0, 'entity_location': 1.0, 'slot_location_0': 1.0, 'intent_inform': 1.0}]
2019-05-13 14:11:59 DEBUG    rasa_core.policies.memoization  - There is a memorised next action '0'
2019-05-13 14:11:59 DEBUG    rasa_core.policies.ensemble  - Predicted next action using policy_0_MemoizationPolicy
2019-05-13 14:11:59 DEBUG    rasa_core.processor  - Predicted next action 'action_listen' with prob 1.00.
2019-05-13 14:11:59 DEBUG    rasa_core.processor  - Action 'action_listen' ended with events '[]'
219.91.191.183 - - [2019-05-13 14:11:59] "GET /webhooks/chatroom/conversations/e2af79b0-bbbe-42f1-be75-af1fc2db2808/say?message=london&uuid=7d179789-320b-410b-af2e-087695a47f3f HTTP/1.1" 200 193 0.118018

logs_of_action_server:
127.0.0.1 - - [2019-05-13 14:11:59] "POST /webhook/ HTTP/1.1" 404 342 0.003401

endpoint.yml file:
action_endpoint:
  url: "http://localhost:5055/webhook/"

FYI: everything working perfect with backend, just not work while using frontend with chatroom.

please let me know how can i fix ASAP this.
thanks

**Comment by GraphGrailAi** [comment]
Seems similar to https://github.com/scalableminds/chatroom/issues/96

I also have an issue but another:

 ```

ERROR    rasa_core.processor  - Encountered an exception while running action 'action_joke'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
127.0.0.1 - - [2019-05-25 21:35:31] "GET /webhooks/chatroom/conversations/581bbacb-9e64-4540-ad8d-0e295218831d/say?message=%D0%BF%D0%BE%D1%88%D1%83%D1%82%D0%B8%20%D0%BF%D1%80%D0%BE%20%D0%9F%D0%BE%D1%80%D0%BE%D1%85%D0%B0&uuid=6c20bb44-f872-461e-916a-703be8d7fc50 HTTP/1.1" 200 166 0.018590

```

**Comment by hotzenklotz** [comment]
Both issues are not related to this Chatroom UI. Use the [Rasa Community](https://forum.rasa.com) forum for help. 

@sachinbanugariya There is an error when executing your custom actions. Seems like URL `http://localhost:5055/webhook/` can Not be found. Make sure you have the Rasa Core SDK configured correctly and running. See http://rasa.com/docs/rasa/core/actions/#custom-actions

@GraphGrailAi Your custom action seems to have errors in the code or the return value is incorrect. Make sure that your costum action runs fine independently of the Chatroom. Look at the logs for a stacktrace or you the CLI chat interface to isolate the issue from the chatroom.
