### ISSUE TITLE
'BotServerInputChannel' object has no attribute 'cors_origins'

### ISSUE THREAD

**Issue by arcontechnologies** [scalableminds/chatroom#11]
I did the integration into bot tutorial example and ended up with this issue:

2018-06-16 16:29:28+0200 [-] "127.0.0.1" - - [16/Jun/2018:14:29:28 +0000] "GET /conversations/82aa233e-91e9-4557-bff6-7b6dc3cdc624/log HTTP/1.1" 500 5554 "http://localhost:8080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
2018-06-16 16:29:30+0200 [-] Unhandled Error
        Traceback (most recent call last):
          File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\twisted\web\server.py", line 257, in render
            body = resrc.render(self)
          File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\klein\resource.py", line 210, in render
            d = defer.maybeDeferred(_execute)
          File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\twisted\internet\defer.py", line 150, in maybeDeferred
            result = f(*args, **kw)
          File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\klein\resource.py", line 204, in _execute
            **kwargs)
        --- <exception caught here> ---
          File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\twisted\internet\defer.py", line 150, in maybeDeferred
            result = f(*args, **kw)
          File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\klein\app.py", line 128, in execute_endpoint
            return endpoint_f(self._instance, *args, **kwargs)
          File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\klein\app.py", line 227, in _f
            return _call(instance, f, request, *a, **kw)
          File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\klein\app.py", line 50, in _call
            result = f(*args, **kwargs)
          File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\rasa_nlu\server.py", line 105, in decorated
            if '*' in self.cors_origins:
        builtins.AttributeError: **'BotServerInputChannel' object has no attribute 'cors_origins'**

any insight what causing this ?

**Comment by normanrz** [comment]
Could you try replacing https://github.com/scalableminds/chatroom/blob/master/rasa_utils/bot_server_channel.py#L94 with `self.cors_origins = [u'*']`?

**Comment by arcontechnologies** [comment]
It works. there is no error anymore. thanks
