### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by fallik** [scalableminds/chatroom#126]
Hi there,

on executing `yarn build` I am getting the following Warnings. Does anyone have any hint on that?

```
(node:12983) UnhandledPromiseRejectionWarning: Error: Could not locate the bindings file. Tried:
 → /chatbot/ui/node_modules/deasync/build/deasync.node
 → /chatbot/ui/node_modules/deasync/build/Debug/deasync.node
 → /chatbot/ui/node_modules/deasync/build/Release/deasync.node
 → /chatbot/ui/node_modules/deasync/out/Debug/deasync.node
 → /chatbot/ui/node_modules/deasync/Debug/deasync.node
 → /chatbot/ui/node_modules/deasync/out/Release/deasync.node
 → /chatbot/ui/node_modules/deasync/Release/deasync.node
 → /chatbot/ui/node_modules/deasync/build/default/deasync.node
 → /chatbot/ui/node_modules/deasync/compiled/13.8.0/darwin/x64/deasync.node
    at bindings (/chatbot/ui/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/chatbot/ui/node_modules/deasync/index.js:30:31)
    at Module._compile (/chatbot/ui/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (/chatbot/ui/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/chatbot/ui/node_modules/parcel-bundler/src/utils/syncPromise.js:1:79)
    at Module._compile (/chatbot/ui/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
(node:12983) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:12983) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✨  Done in 0.67s.
```

**Comment by hotzenklotz** [comment]
Not sure I understand the problem here. Is the Chatroom building or not?

**Comment by fallik** [comment]
Unfortunately it is not

**Comment by hotzenklotz** [comment]
I just tried building it again and I had no trouble. :-/  What versions of `yarn` and `node` are you using? 

```
→ node --version
v12.3.1

→ yarn --version
1.16.0
```

**Comment by hotzenklotz** [comment]
Wait a  minute! Are you sure you reporting this problem to the right GitHub repo? Our repo does not include the path `/chatbot/ui/` or the node module `deasync`...
