### ISSUE TITLE
yarn install is throwing error

### ISSUE THREAD

**Issue by poojasingh-code** [scalableminds/chatroom#159]
After cloning the repository I followed the development dependency process as mentioned in readme file, however getting errors. please help

![f](https://user-images.githubusercontent.com/73940111/112425218-b6012200-8d5b-11eb-9dde-7fb39219eed0.PNG)

**Comment by kmanadkat** [comment]
@normanrz `yarn install` is failing for mac too

```shell
AE_C02Z94A6LVCG:chatroom xeuser$ yarn
yarn install v1.22.10
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
[-/5] ⠂ waiting...
[2/5] ⠂ node-sass
[3/5] ⠂ fsevents
[4/5] ⠂ deasync
error /Users/xeuser/Documents/OS Contribution/chatroom/node_modules/deasync: Command failed.
Exit code: 1
Command: node ./build.js
Arguments: 
Directory: /Users/xeuser/Documents/OS Contribution/chatroom/node_modules/deasync
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@14.12.0 | darwin | x64
gyp info find Python using Python version 3.7.9 found at "/usr/local/bin/python3"
gyp info spawn /usr/local/bin/python3
gyp info spawn args [
gyp info spawn args   '/Users/xeuser/.nvm/versions/node/v14.12.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/xeuser/Documents/OS Contribution/chatroom/node_modules/deasync/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/xeuser/.nvm/versions/node/v14.12.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/xeuser/Library/Caches/node-gyp/14.12.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/xeuser/Library/Caches/node-gyp/14.12.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/xeuser/.nvm/versions/node/v14.12.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/xeuser/Library/Caches/node-gyp/14.12.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/xeuser/Documents/OS Contribution/chatroom/node_modules/deasync',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/deasync/src/deasync.o
clang: error: no such file or directory: 'Contribution/chatroom/node_modules/node-addon-api'
make: *** [Release/obj.target/deasync/src/deasync.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/xeuser/.nvm/versions/node/v14.12.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 20.3.0
gyp ERR! command "/Users/xeuser/.nvm/versions/node/v14.12.0/bin/node" "/Users/xeuser/.nvm/versions/node/v14.12.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/xeuser/Documents/OS Contribution/chatroom/node_modules/deasync
gyp ERR! node -v v14.12.0
```

Not able to run the code after cloning repo.

**Comment by hadisd5** [comment]
just install node-sass version 5.0.0

**Comment by hadisd5** [comment]
> After cloning the repository I followed the development dependency process as mentioned in readme file, however getting errors. please help
> 
> ![f](https://user-images.githubusercontent.com/73940111/112425218-b6012200-8d5b-11eb-9dde-7fb39219eed0.PNG)

Just install node-sass version 5.0.0
