### ISSUE TITLE
No Response to the Chatroom

### ISSUE THREAD

**Issue by PravinrajV** [scalableminds/chatroom#42]
I have installed and followed the instructions.
![04_ui_capture](https://user-images.githubusercontent.com/31581909/45912387-49a1b280-bdee-11e8-8ef8-8e20eaad5071.PNG)
![03_bot_capture](https://user-images.githubusercontent.com/31581909/45912388-49a1b280-bdee-11e8-8f75-de14dc600313.PNG)
![02_actions_capture](https://user-images.githubusercontent.com/31581909/45912389-4a3a4900-bdee-11e8-82d6-0bfbdc964065.PNG)
![01_yarn_capture](https://user-images.githubusercontent.com/31581909/45912390-4a3a4900-bdee-11e8-84e1-6e60febfe342.PNG)

I have 3 terminals running --> Yarn serve, actions, bot.
When I type in the chatroom, I see that in the Bot terminal, but i dont get any response displayed in the Chatroom.

Screenshots attached.
Please help.

**Comment by PravinrajV** [comment]
I checked the browser --> dev tools --> network tab and can see the below:

> <title>404 Not Found</title>
> <h1>Not Found</h1>
> <p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>
>

**Comment by oldmonkABA** [comment]
I am getting the same error

**Comment by PravinrajV** [comment]
any help please..

**Comment by hotzenklotz** [comment]
Looks like you are already using the latest version of Rasa Core (0.11.x). Unfortunately, we haven't had a chance to update the connector yet, but will do so soon. Check issue #39 

You could try down-grading to Rasa Core 0.10.x in the meantime.

**Comment by PravinrajV** [comment]
@hotzenklotz I tried downgrading to rasa code 0.10.4 and get the below error:
```

Using TensorFlow backend.
Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\PRAVIN\Chatbot\Uibot\rasa_utils\bot.py", line 59, in <module>
    agent = Agent.load(cmdline_args.core, interpreter=cmdline_args.nlu)
  File "C:\Program Files\Python35\lib\site-packages\rasa_core\agent.py", line 81, in load
    ensemble = PolicyEnsemble.load(path)
  File "C:\Program Files\Python35\lib\site-packages\rasa_core\policies\ensemble.py", line 198, in lo
ad
    policy = policy_cls.load(policy_path)
  File "C:\Program Files\Python35\lib\site-packages\rasa_core\policies\keras_policy.py", line 264, i
n load
    model_arch = cls._load_model_arch(path, meta)
  File "C:\Program Files\Python35\lib\site-packages\rasa_core\policies\keras_policy.py", line 240, i
n _load_model_arch
    arch_file = os.path.join(path, meta["arch"])
KeyError: 'arch'

```

**Comment by hotzenklotz** [comment]
Well, the traceback above has nothing to do with the Chatroom. Looks like you have a problem with loading your Rasa Core model. Have you retrained you Core model after downgrading?

**Comment by PravinrajV** [comment]
Looks like after downgrading, i have some issues with retraining the core model.


```
Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python35\lib\site-packages\rasa_core\train.py", line 155, in <module>
    additional_arguments)
  File "C:\Program Files\Python35\lib\site-packages\rasa_core\train.py", line 106, in train_dialogue
_model
    max_history=max_history))])
  File "C:\Program Files\Python35\lib\site-packages\rasa_core\agent.py", line 51, in __init__
    self.domain = self._create_domain(domain)
  File "C:\Program Files\Python35\lib\site-packages\rasa_core\agent.py", line 390, in _create_domain

    return TemplateDomain.load(domain)
  File "C:\Program Files\Python35\lib\site-packages\rasa_core\domain.py", line 411, in load
    return cls.load_from_yaml(read_file(filename), action_factory=action_factory)
  File "C:\Program Files\Python35\lib\site-packages\rasa_core\domain.py", line 431, in load_from_yam
l
    **additional_arguments
  File "C:\Program Files\Python35\lib\site-packages\rasa_core\domain.py", line 511, in __init__
    action_factory, action_classes, action_names, templates)
  File "C:\Program Files\Python35\lib\site-packages\rasa_core\domain.py", line 518, in instantiate_a
ctions
    custom_actions = action_factory(action_classes, action_names, templates)
  File "C:\Program Files\Python35\lib\site-packages\rasa_core\actions\factories.py", line 77, in loc
al_action_factory
    actions.append(_action_class(name))
  File "C:\Program Files\Python35\lib\site-packages\rasa_core\actions\factories.py", line 69, in _ac
tion_class
    "with `utter_`. Error: {}".format(action_name, e))
ValueError: Action 'action_joke' doesn't correspond to a template / action. Module doesn't contain a
 class with this name. Remember to prefix actions that should utter a template with `utter_`. Error:
 'action_joke'
```

**Comment by hotzenklotz** [comment]
@PravinrajV Your stack trace has nothing to do with the chatroom. I looks like you are missing the action `action_joke` in your domain file. Make sure to add it there.

**Comment by PravinrajV** [comment]
It is there. the same domain file works fine with the higher version of the rasa core. Thats why it is confusing..

**Comment by Brijeshlakkad** [comment]
I m using rasa_core 0.11.12
and using
1. $ python -m rasa_core_sdk.endpoint --actions actions (To run custom actions)
2. $ yarn serve
3. $ python -m rasa_utils.bot  -d models/dialogue -u models/nlu/default/bank_nlu
but i can not get any responses at frontend.
```
<html>
<head>
  <link rel="stylesheet" href="https://npm-scalableminds.s3.eu-central-1.amazonaws.com/@scalableminds/chatroom@master/dist/Chatroom.css" />
</head>
<body>
  <div class="chat-container"></div>

  <script src="https://npm-scalableminds.s3.eu-central-1.amazonaws.com/@scalableminds/chatroom@master/dist/Chatroom.js"/></script>
  <script type="text/javascript">
    var chatroom = window.Chatroom({
      host: "http://localhost:5005",
      title: "Chat with Mike",
      container: document.querySelector(".chat-container"),
      welcomeMessage: "Hi, I am Mike. How may I help you?"
    });
    chatroom.openChat();
  </script>
</body>
</html>
```

**Comment by Brijeshlakkad** [comment]
@hotzenklotz can see this please

**Comment by Brijeshlakkad** [comment]
@hotzenklotz can you please check this
