### ISSUE TITLE
ImportError: No module named bot_server_channel

### ISSUE THREAD

**Issue by azizullah2017** [scalableminds/chatroom#45]
```
python -m rasa_utils.bot -d models/current/dialogue -u models/nlu/Auto/Auto

/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/user/Documents/Ui Bot/rasa_utils/bot.py", line 10, in <module>
    from rasa_core.agent import Agent
  File "rasa_core/agent.py", line 40, in <module>
    from bot_server_channel import BotServerInputChanne
ImportError: No module named bot_server_channel
```

**Comment by hotzenklotz** [comment]
Which Core version are you running? Version 0.11.x is still incompatible until we merge PR #43 

Further there seems to be a typo in `from bot_server_channel import BotServerInputChanne`. The `L` is missing from `BotServerInputChannel`

**Comment by azizullah2017** [comment]
withour pasting the code in agent.py
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/user/Documents/Ui Bot/rasa_utils/bot.py", line 61, in <module>
    agent.handle_channel(channel, message_preprocessor=preprocessor)
AttributeError: 'Agent' object has no attribute 'handle_channel'
```

**Comment by hotzenklotz** [comment]
Check out my answer here: https://github.com/scalableminds/chatroom/issues/47#issuecomment-428184160 That should help.

I have since updated the readme.
