### ISSUE TITLE
AvailableEndpoints ImportError when running bot.py

### ISSUE THREAD

**Issue by abarthakur** [scalableminds/chatroom#65]
When I tried running

`python -m rasa_utils.bot -d models/current/dialogue -u models/current/model_20181101-200133/`

I get the error -

```
Traceback (most recent call last):
  File "/Users/abarthak/Downloads/installations/miniconda3/envs/rasapy36/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/abarthak/Downloads/installations/miniconda3/envs/rasapy36/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/abarthak/chatbot_sandbox/starter-pack-rasa-stack/rasa_utils/bot.py", line 26, in <module>
    from rasa_core.utils import read_yaml_file, AvailableEndpoints
ImportError: cannot import name 'AvailableEndpoints'
```

My Rasa Core version is 0.11.1, rasa_core_sdk is 0.11.5.

Any clue why this is happening? Any help would be great thanks!

**Comment by hotzenklotz** [comment]
Interesting. Looks like the `AvailableEndpoints ` class was only introduced in Rasa Core 0.11.4: https://github.com/RasaHQ/rasa_core/blob/0.11.4/rasa_core/utils.py#L585

Make sure to upgrade to Rasa Core version ´0.11.4`.
