### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 58 column 2 (char 1012)

### ISSUE THREAD

**Issue by SandraAnildas** [scalableminds/chatroom#98]
I get the following error in my running rasa server console window when i send a message in my bot.

2019-04-26 00:40:22 INFO     root  - Rasa process starting
2019-04-26 00:40:23 INFO     rasa_nlu.components  - Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Traceback (most recent call last):
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Hp\Desktop\Quinn\rasa_utils\bot.py", line 150, in <module>
    tracker_store=_tracker_store)
  File "C:\Users\Hp\Desktop\Quinn\rasa_utils\bot.py", line 120, in load_agent
    action_endpoint=endpoints.action)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\agent.py", line 262, in load
    ensemble = PolicyEnsemble.load(path) if path else None
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\policies\ensemble.py", line 202, in load
    metadata = cls.load_metadata(path)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\policies\ensemble.py", line 163, in load_metadata
    metadata = json.loads(utils.read_file(os.path.abspath(metadata_path)))
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 58 column 2 (char 1012)

**Comment by SandraAnildas** [comment]
Kindly help............

**Comment by jstriebel** [comment]
This is an error when loading your NLU model, it has nothing to do with the `chatroom` component, which this repository is about. You can try to get help at the [Rasa Forum](https://forum.rasa.com).
